### ISSUE TITLE
建议提供更新锁屏而不更新壁纸的功能

### ISSUE THREAD

**Issue by comzyh** [oxoooo/earth#1]
壁纸是个地球其实蛮乱的，但是更新锁屏就很漂亮啦！

**Comment by xingrz** [comment]
这个问题请咨询你的手机厂商，It's none of my business.

**Comment by bitdust** [comment]
真相就是安卓手机没有更新锁屏图片的接口。。。起码没有一个统一的接口

**Comment by xingrz** [comment]
@bitdust 应该这么说…

**我只对原生 Android 负责。**

> 只改锁屏不改壁纸？
> 改锁屏？
> 锁屏是啥？
> 难道你的手机锁屏不是你的壁纸？
> 好神奇喔~

**Comment by bitdust** [comment]
@xingrz 
我可耻的笑了~
