### ISSUE TITLE
Android 始终无法更新壁纸

### ISSUE THREAD

**Issue by Zhang-Siyang** [oxoooo/earth#10]
无论是从酷安还是Play下载，应用均无法将新的壁纸拉下来，请看截图：

![](https://i.imgur.com/7WCggaE.png)

此时应为：

![正常情况](https://i.imgur.com/fa0ZOEb.png)

不知道我应该提供什么信息给您？我的手机是Mokee71.2[Android 7.1.2], 开了Shadowsocksr，也试过在路由器上配置Shadowsocksr，但均无法更新；我在Windows上使用[EarthLiveSharp v3.7](https://github.com/bitdust/EarthLiveSharp)可以正常更新

>EarthLiveSharp 使用了官方源

**Comment by xingrz** [comment]
服务器欠费。我们没钱了。

**Comment by Zhang-Siyang** [comment]
@xingrz 唔，

1. 不是获得了又拍云的赞助吗？
2. 所有客户端一个月的流量开支有多少？
3. 可不可以增加一个设置，即：使用自己的服务器或CDN服务器，就像[EarthLiveSharp](https://github.com/bitdust/EarthLiveSharp)一样？

> 这 [即使停用，也不是使用源站资源]是对源服务器的保护吗？十分佩服

**Comment by xingrz** [comment]
@Zhang-Siyang 

1. 又拍的赞助是创业赞助，只有一年免费期
2. 最火的时候一个月能烧 2TB。但坦白地说，今年因为疏于运作，已经下跌到十几 GB 了
3. 多分辨率使用了又拍云的在线处理特性。虽然之前我们用过七牛云，但是因为各家 CDN 的这个特性是不一样的，需要分别对待。我们想做一个小而美的开箱即用的应用，而不是一个太倾向 geek 的需要配置的玩意
4. 的确，我们不希望因为这个应用的用户增长而给源站带来额外的负担。无论馒头地球增加多少用户，所有流量都是由我们自己承担的，对源站而言只是多了一个用户。毕竟大家都是公益项目。从这个角度来说如果实现第 3 点就会违背这个原则

**Comment by nvan233** [comment]
能不能做一个收费版出来？我真的很喜欢这个软件……

**Comment by Zhang-Siyang** [comment]
每个月 2TB 这种的话，有没有考虑过租一台VPS来用？Vultr的那些廉价服务器流量挺大的呀，还可以用
 Cloudflare 的免费CDN（小心使用协议，您这个好像是想做成商业项目）

**Comment by xingrz** [comment]
@Zhang-Siyang 这个问题当年已经讨论过了。VPS 是单点的，国外服务器更不可取。我们需要的是国内、稳定，各地区速度良好。

**Comment by Zhang-Siyang** [comment]
@xingrz 国外服务器更不可取？暂时不推向国外吗？我作为一个用户的想法是：当源服务器分布更新后能在三五秒内推送到我的手机那是很好的，但你要是滞后个五六分钟也没什么。用户要是都这么想，大概会减轻服务器不小的压力。

作为一个普通用户，不知道说这些是不是有点指手画脚；
对Github的issues不是很了解，现在是到了要关闭这个issues的时候吗？

**Comment by xingrz** [comment]
用国外服务器基本上约等于在国内连不上了。
