### ISSUE TITLE
地址变了麻烦更新下

### ISSUE THREAD

**Issue by qzwl** [oxoooo/earth#16]
https://himawari.asia/

**Comment by xingrz** [comment]
感谢提醒。已修复。

**Comment by qzwl** [comment]
> 感谢提醒。已修复。

还以为联系不上你了

**Comment by qzwl** [comment]
> 感谢提醒。已修复。

好像更新比较缓慢。不知道是不是新网站限制了抓取？

**Comment by qzwl** [comment]
https://ncthmwrwbtst.cr.chiba-u.ac.jp/img/D531106
别的地方看到这个域名。

**Comment by xingrz** [comment]
> > 感谢提醒。已修复。
> 
> 好像更新比较缓慢。不知道是不是新网站限制了抓取？

我这边监测正常。

**Comment by qzwl** [comment]
> > > 感谢提醒。已修复。
> > 
> > 好像更新比较缓慢。不知道是不是新网站限制了抓取？
> 
> 我这边监测正常。

25号18点31分以后就没更新了。难道又挂了？

**Comment by xingrz** [comment]
> > > > 感谢提醒。已修复。
> > > 
> > > 
> > > 好像更新比较缓慢。不知道是不是新网站限制了抓取？
> > 
> > 
> > 我这边监测正常。
> 
> 25号18点31分以后就没更新了。难道又挂了？

![S20928-10052618](https://user-images.githubusercontent.com/288288/192671069-15b879db-479e-4fa7-8282-746df9bc6218.png)

一切正常

**Comment by qzwl** [comment]
> > > > > 感谢提醒。已修复。
> > > > 
> > > > 
> > > > 好像更新比较缓慢。不知道是不是新网站限制了抓取？
> > > 
> > > 
> > > 我这边监测正常。
> > 
> > 25号18点31分以后就没更新了。难道又挂了？
> 
> ![S20928-10052618](https://user-images.githubusercontent.com/288288/192671069-15b879db-479e-4fa7-8282-746df9bc6218.png)
> 
> 一切正常

我现在看也更新了。🥺
