### ISSUE TITLE
有时图片会变灰

### ISSUE THREAD

**Issue by Iamanorange** [oxoooo/earth#2]
有时图片会变灰，更改设置后能变回彩色，未能稳定重现问题。
设备是运行CM12(Android5.1.1)的Amazon fire(5th generation)。

**Comment by Iamanorange** [comment]
![screenshot_2016-01-13-06-28-20](https://cloud.githubusercontent.com/assets/6018925/12278918/ea4d81d2-b9be-11e5-8080-22f6bf32d2c6.png)

**Comment by xingrz** [comment]
向日葵8官网返回的数据就是这样的，不是我们的问题。
