### ISSUE TITLE
我为馒头地球操碎心系列

### ISSUE THREAD

**Issue by bitdust** [oxoooo/earth#4]
首先恭喜馒头地球解决了流量问题
然后就是夏天要来了，台风季也要来了，借着这股南风，我预测馒头地球要火，不是小火，而会一片大火。
每天没事刷刷屏幕看看台风飞到哪里了，朋友圈分享个截图:啊啊啊啊台风要来了，我好怕怕～(恐惧脸)

那么问题来了，馒头地球有木有什么 发展规划/推广计划/(变现计划)/洗白计划 什么的吗？

一个思路:
比如说跟向日葵官方合作下，要个授权或者直接换层皮把项目捐给官方，变成官方应用什么的

----一个为了用馒头地球，专门换了台手机的忠实用户

**Comment by bitdust** [comment]
还有就是 iOS端真的没戏么

**Comment by xingrz** [comment]
iOS 可能只支持「打开静静地看着装逼」模式 `_(:зゝ∠)_`

**Comment by mjason** [comment]
因为我们不会日文啊

**Comment by bitdust** [comment]
我不懂iOS，估计是iOS实时更新图片不方便～那能不能做成订阅形式的？馒头地球-大事件 馒头地球-昨日重现 什么的，毕竟这是移动端半壁江山。
然后，我觉得不管怎样，这个应用以后的发展是绕不开和官方的接触～从那个漂亮的官方网站来看，我猜他们的心态会比较开放的。如果顺利的话，这也会是走向国际的成功一步，上个hacknews前十什么的不是梦。

**Comment by xingrz** [comment]
不是，是 iOS 不能作为壁纸。所以只能是打开个 App 静静地观看（严肃脸

**Comment by bitdust** [comment]
好吧，，iOS用户好可怜

**Comment by xingrz** [comment]
至于官方的事情，其实一直有这个想法，只不过缺少个搭桥的。之前发过邮件询问，石沉大海了…

**Comment by bitdust** [comment]
明白了，刚才还专门去看了下授权说明。。
才发现托管网站的NICT这个机构有点大，规矩不少，还真不太容易联系上。
