### ISSUE TITLE
The app doesn't work on MIUI with default setting

### ISSUE THREAD

**Issue by helloqiu** [oxoooo/earth#6]
I try this app this morning and I find the earth doesn't change during the day.
So I run logcat and that's what I get:

```
05-26 21:08:00.481  2233  2374 I AutoStartManagerService:   
MIUILOG- Reject service :Intent { act=android.content.SyncAdapter cmp=ooo.oxo.apps.earth/.sync.EarthsSyncService (has extras) } userId : 0 uid : 10118 
05-26 21:18:24.096  2233  2374 I AutoStartManagerService: 
MIUILOG- Reject service :Intent { act=android.content.SyncAdapter cmp=ooo.oxo.apps.earth/.sync.EarthsSyncService (has extras) } userId : 0 uid : 10118 
05-26 21:28:24.098  2233  2374 I AutoStartManagerService: 
MIUILOG- Reject service :Intent { act=android.content.SyncAdapter cmp=ooo.oxo.apps.earth/.sync.EarthsSyncService (has extras) } userId : 0 uid : 10118
```

MIUI just reject the service!
I finally solve this problem.I change the permission of visit user's account from ask to always allow.
But I think most users don't know how to deal with this kind of problems.So why not add another way to sync data when the account sync is down.

**Comment by xingrz** [comment]
Hi @helloqiu, thank you for your feedback.

As you see the sync service is rejected by a so-called `AutoStartManagerService` of MIUI.

MIUI believes that any auto-starting service is _"evil"_. We have no idea how to by-pass this _"protection"_ without taking any truly EVIL measure.

But luckily and sadly, we decided to add an EVIL MODE switch to keep the sync service lives as long as we can (and consume battery as more as it is expected) in the next release. I hope that would make things work properly and make MI company happy.

**Comment by helloqiu** [comment]
Thank you for your quick response. @xingrz 
Looking forward to the new version. :)
