### ISSUE TITLE
今天开始不能自动更新了

### ISSUE THREAD

**Issue by TTTPOB** [oxoooo/earth#7]
（感觉很奇怪应用内也没有找到开发者邮箱我就跑到这里来了）

**Comment by xingrz** [comment]
找对地方了。

今天13点开始服务故障，我们正在处理。

**Comment by TTTPOB** [comment]
原来是这样呢23333
谢谢你们了（很喜欢你们的应用^ω^）
2016年6月13日 21:01于 XiNGRZ notifications@github.com写道：找对地方了。

今天13点开始服务故障，我们正在处理。
