### ISSUE TITLE
[Feature] Let my position face me

### ISSUE THREAD

**Issue by leetking** [oxoooo/earth#9]
Can I rotate the earth to let China face me？

**Comment by YueLengM** [comment]
你总不能让同步卫星换个地方吧……人家卫星就是拍太平洋的

**Comment by bitdust** [comment]
[地理小科普]
同步卫星轨道只存在于赤道上空。
PS：这是日本家的卫星，结果只能发到澳大利亚上空，不能经过自家头顶，想想日本人该多怨念啊

**Comment by leetking** [comment]
好吧。难道能办到这个只有同步卫星？

**Comment by YueLengM** [comment]
非同步卫星拍摄的地方就不一样了

**Comment by leetking** [comment]
虽然非同步也许只是后期处理复杂，如果有能拍摄面向中国的就最好了

**Comment by xingrz** [comment]
@leetking 非同步卫星并不是「后期处理复杂」，而是根本无法固定在任何一个非赤道位置的上空。

建议参考高中一年级物理知识。

**Comment by xingrz** [comment]
另外：

1. 我们没有控制向日葵八号往哪飞的权利
2. 目前人类还真的只有向日葵八号一颗同步的、能拍摄彩色照片的卫星
3. 当然，我们也没有钱自己发射一颗卫星上去
